
version: '3.7'
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'chinmina/chinmina-token']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester:v4.1.1
    volumes:
      - ".:/plugin"