name: Github App Auth
description: |
  Adds a Git credential helper that authorizes a pipeline to access its Github
  using HTTPS and a time-limited token.

  The helper agent (separate) is accessed via HTTP, using the Buildkite Agent
  OIDC token as its authorization.
author: https://github.com/chinmina
requirements: []
configuration:
  properties: {}
  additionalProperties: false