name: Chinmina Token
description: |
  Provides GitHub token retrieval from Chinmina in two modes:

  **Library Mode** (no `environment` parameter): Adds `chinmina_token` script to
  PATH for manual token retrieval in agent scripts.

  **Environment Mode** (`environment` parameter present): Automatically exports
  tokens to specified environment variables.

  The helper agent (separate) is accessed via HTTP, using the Buildkite Agent
  OIDC token as its authorization.
author: https://github.com/chinmina
requirements:
  - jq
configuration:
  properties:
    chinmina-url:
      type: string
      description: |
        The URL of the Chinmina Bridge agent that creates a token for a pipeline.

        Priority: plugin parameter > CHINMINA_DEFAULT_URL environment variable >
        CHINMINA_TOKEN_LIBRARY_FUNCTION_CHINMINA_URL. Required via at least one mechanism.
    audience:
      type: string
      description: |
        (Default: `chinmina:default`) The audience to use for the Buildkite OIDC
        JWT that is sent to the vendor agent. Must match the setting in the vendor agent.

        Priority: plugin parameter > CHINMINA_DEFAULT_AUDIENCE environment variable >
        CHINMINA_TOKEN_LIBRARY_FUNCTION_AUDIENCE > "chinmina:default".
    environment:
      type: array
      description: |
        Array of environment variable assignments in the format 'VAR_NAME=org:profile'.
        Each entry exports an environment variable containing a token from the specified profile.
        When this parameter is present, the plugin operates in Environment Mode (PATH is not modified).
  additionalProperties: false
  required: []
