#!/bin/bash

main() {
  local url="$1"

  dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
  # shellcheck source=../lib/download.sh
  . "$dir/../lib/download.sh"

  validate_tooling "$cmd"
  
  if [ -z "${url}" ]; then
    echo -e "\e[31murl is not specified\e[0m" >/dev/stderr
    exit 1
  fi

  release_filename=$(get_release_filename "$url")
  echo "$release_filename"

  local called_from_dir
  called_from_dir=$(pwd)
  download_release "$url" "$release_filename" "$called_from_dir"
}

main "$@"